# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('cost', models.FloatField(default=0)),
                ('postcost', models.FloatField(default=0)),
                ('gathering', models.FloatField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pay', models.BooleanField(default=False)),
                ('gathering', models.FloatField(default=0, max_length=20)),
                ('total', models.FloatField(default=0)),
                ('postage', models.FloatField(default=0)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Buy')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('secret', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('photo', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Good_lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good_specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('specificati', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_price', models.FloatField(blank=True, default=0, null=True)),
                ('purchase_currency', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HKD', models.FloatField()),
                ('CNY', models.FloatField()),
                ('KRW', models.FloatField()),
                ('AUD', models.FloatField()),
                ('USD', models.FloatField()),
                ('JPY', models.FloatField()),
                ('GBP', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wx', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('craete_time', models.DateTimeField(auto_now_add=True)),
                ('recently_time', models.DateTimeField(auto_now=True)),
                ('invite_code', models.CharField(max_length=12)),
                ('profit', models.FloatField(default=0)),
                ('saleroom', models.FloatField(default=0)),
                ('get_list', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='good_lable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
        migrations.AddField(
            model_name='good',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybuy.Good_lable'),
        ),
        migrations.AddField(
            model_name='good',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
        migrations.AddField(
            model_name='buy_list',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Client'),
        ),
        migrations.AddField(
            model_name='buy_good',
            name='buy_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Buy_list'),
        ),
        migrations.AddField(
            model_name='buy_good',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Good'),
        ),
        migrations.AddField(
            model_name='buy_good',
            name='good_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybuy.Good_specification'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
    ]
