# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('pay', models.BooleanField()),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Buy')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=12)),
                ('specificati', models.CharField(max_length=80)),
                ('photo', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wx', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('recently_time', models.DateTimeField(auto_now=True)),
                ('times', models.IntegerField(max_length=20)),
                ('invite_code', models.IntegerField(max_length=12)),
                ('get_list', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
        migrations.AddField(
            model_name='buy_list',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Client'),
        ),
        migrations.AddField(
            model_name='buy_good',
            name='buy_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Buy_list'),
        ),
        migrations.AddField(
            model_name='buy_good',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Good'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
    ]
