# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_good',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='times',
            field=models.IntegerField(),
        ),
    ]
