# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0002_auto_20180326_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good_lable',
            new_name='Category',
        ),
    ]
