# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0002_auto_20171228_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='cost',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='buy',
            name='gathering',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='buy_good',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
