# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0003_auto_20180103_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('secret', models.CharField(max_length=40)),
            ],
        ),
    ]
