# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0004_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='purchase_currency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='good',
            name='purchase_price',
            field=models.FloatField(default=0, max_length=12),
        ),
    ]
