# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0004_auto_20180326_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='remark',
            field=models.CharField(blank=True, max_length=740, null=True),
        ),
        migrations.AlterField(
            model_name='good_specification',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='good_specification',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
    ]
