# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0005_auto_20180108_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HKD', models.FloatField()),
                ('KRW', models.FloatField()),
                ('AUD', models.FloatField()),
                ('USD', models.FloatField()),
                ('JPY', models.FloatField()),
                ('GBP', models.FloatField()),
                ('CNY', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
