# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0005_auto_20180327_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybuy.Category'),
        ),
    ]
