# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0006_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='cost',
            field=models.FloatField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
