# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0007_auto_20180329_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_list',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybuy.Client'),
        ),
    ]
