# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0007_auto_20180111_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='cost',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
