# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0008_auto_20180111_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buy_list',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
