# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0009_auto_20180329_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_good',
            name='spe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybuy.Good_specification'),
        ),
        migrations.AlterField(
            model_name='buy_good',
            name='buy_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mybuy.Buy_list'),
        ),
    ]
