# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0009_auto_20180111_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_list',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
