# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0010_auto_20180111_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='saleroom',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='get_list',
            field=models.BooleanField(default=True),
        ),
    ]
