# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0010_auto_20180331_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('Confirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=600)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='confirm_inform',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.Inform'),
        ),
        migrations.AddField(
            model_name='confirm_inform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybuy.User'),
        ),
    ]
