# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0011_auto_20180402_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm_inform',
            old_name='Confirm',
            new_name='confirm',
        ),
    ]
