# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0011_auto_20180117_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_list',
            name='gathering',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='buy_list',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
