# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0012_auto_20180402_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_list',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
