# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0012_auto_20180119_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_good',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy_good',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy_list',
            name='postage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='photo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='purchase_price',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='specificati',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
