# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0014_auto_20180122_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='cost',
            field=models.FloatField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
