# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybuy', '0015_auto_20180122_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='postcost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
